language: erlang
notifications:
  recipients:
    - cabo@tzi.org
otp_release:
  - R16B02
before_install:
  - git clone git://github.com/elixir-lang/elixir --depth 1
  - make -C elixir
before_script: "export PATH=`pwd`/elixir/bin:$PATH"
script: "MIX_ENV=test mix do deps.get, test"
